import type { components, operations, paths } from "@labldap/openapi";

export type { components, operations, paths };

export type User = components["schemas"]["User"];
export type UserSpec = components["schemas"]["UserSpec"];
export type UserPatch = components["schemas"]["UserPatch"];
export type UserPage = components["schemas"]["UserPage"];
export type Group = components["schemas"]["Group"];
export type GroupSpec = components["schemas"]["GroupSpec"];
export type GroupPage = components["schemas"]["GroupPage"];
export type MemberRef = components["schemas"]["MemberRef"];
export type MemberList = components["schemas"]["MemberList"];
export type MembershipSummary = components["schemas"]["MembershipSummary"];
export type PasswordBody = components["schemas"]["PasswordBody"];
export type AttrKV = components["schemas"]["AttrKV"];
export type SessionView = components["schemas"]["SessionView"];
export type SessionCreate = components["schemas"]["SessionCreate"];
export type SessionCreated = components["schemas"]["SessionCreated"];
export type Problem = components["schemas"]["Problem"];
export type HealthStatus = components["schemas"]["HealthStatus"];
export type Scope = components["schemas"]["Scope"];
export type Capabilities = components["schemas"]["Capabilities"];
export type Baseline = components["schemas"]["Baseline"];
export type Diagnostics = components["schemas"]["Diagnostics"];
export type AuditEvent = components["schemas"]["AuditEvent"];
export type AuditPage = components["schemas"]["AuditPage"];
export type BuildInfo = components["schemas"]["BuildInfo"];
export type SearchQuery = components["schemas"]["SearchQuery"];
export type SearchPage = components["schemas"]["SearchPage"];
export type SearchEntry = components["schemas"]["SearchEntry"];
export type SuffixList = components["schemas"]["SuffixList"];
export type TreeQuery = components["schemas"]["TreeQuery"];
export type TreePage = components["schemas"]["TreePage"];
export type TreeNode = components["schemas"]["TreeNode"];
export type EntrySpec = components["schemas"]["EntrySpec"];
export type EntryPatch = components["schemas"]["EntryPatch"];
export type EntryMove = components["schemas"]["EntryMove"];
export type DirectoryEntry = components["schemas"]["DirectoryEntry"];
export type BindTestBody = components["schemas"]["BindTestBody"];
export type BindTestResult = components["schemas"]["BindTestResult"];
export type RootDSE = components["schemas"]["RootDSE"];
export type ObjectClass = components["schemas"]["ObjectClass"];
export type AttributeType = components["schemas"]["AttributeType"];
export type Schema = components["schemas"]["Schema"];
export type ResetRequest = components["schemas"]["ResetRequest"];
export type ResetStatus = components["schemas"]["ResetStatus"];
