package main

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
)

func main() {
	if err := check(); err != nil {
		fmt.Fprintf(os.Stderr, "gencheck: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("gencheck: ok")
}

func check() error {
	mod, err := os.ReadFile("go.mod")
	if err != nil {
		return err
	}
	text := string(mod)
	if !strings.Contains(text, "toolchain go1.26.5") {
		return fmt.Errorf("go.mod missing pinned toolchain go1.26.5")
	}
	if !strings.Contains(text, "go 1.26\n") {
		return fmt.Errorf("go.mod missing language version go 1.26")
	}
	pkg, err := os.ReadFile("frontend/package.json")
	if err != nil {
		return err
	}
	if !strings.Contains(string(pkg), `"packageManager": "pnpm@10.14.0"`) {
		return fmt.Errorf("frontend/package.json packageManager pin drifted")
	}
	if _, err := os.Stat("frontend/pnpm-lock.yaml"); err != nil {
		return fmt.Errorf("frontend/pnpm-lock.yaml missing: %w", err)
	}
	mk, err := os.ReadFile("Makefile")
	if err != nil {
		return err
	}
	makeText := string(mk)
	if !strings.Contains(makeText, "github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.8.0") {
		return fmt.Errorf("Makefile missing oapi-codegen v2.8.0 pin")
	}
	if !strings.Contains(makeText, "openapi-typescript@7.13.0") {
		return fmt.Errorf("Makefile missing openapi-typescript@7.13.0 pin")
	}
	goGen, err := os.ReadFile("api/generated/types.gen.go")
	if err != nil {
		return fmt.Errorf("generated Go types missing: %w", err)
	}
	if !strings.Contains(string(goGen), "Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0") {
		return fmt.Errorf("api/generated/types.gen.go missing oapi-codegen v2.8.0 header")
	}
	tsGen, err := os.ReadFile("api/generated/typescript/schema.d.ts")
	if err != nil {
		return fmt.Errorf("generated TypeScript types missing: %w", err)
	}
	if !strings.Contains(string(tsGen), "auto-generated by openapi-typescript") {
		return fmt.Errorf("api/generated/typescript/schema.d.ts missing openapi-typescript header")
	}
	if _, err := os.Stat(".git"); err == nil {
		cmd := exec.Command("git", "diff", "--exit-code", "--", "api/generated/types.gen.go", "api/generated/typescript/schema.d.ts")
		cmd.Stdout = os.Stderr
		cmd.Stderr = os.Stderr
		if err := cmd.Run(); err != nil {
			return fmt.Errorf("api/generated drifted from make generate: %w", err)
		}
	}
	return nil
}
