package parity

import (
	"os"
	"strings"
	"testing"
)

// TestNativeContractBaseline runs the full Contract case list and the
// CAND probe set against the in-process native engine — no Docker — and
// verifies the outcomes against the committed delta ledger's native
// columns. This keeps `go test ./...` green and meaningful on machines
// without the 389 oracle: a native behavior drift fails here even when
// the dual-engine run is not possible.
//
// The ledger is (re)generated by the dual-engine integration run:
//
//	PARITY_UPDATE_LEDGER=1 go test -tags integration ./test/parity/
func TestNativeContractBaseline(t *testing.T) {
	fx := compileFixture(t)
	ne := startNative(t, fx)
	defer ne.close(t)

	cases := runContract(t, fx, ne)
	cands := runCandidates(t, fx, ne)

	golden := loadLedger(t)

	// Shape checks at parent level: a drifted ledger must stop the run
	// before the index-driven comparisons below (a subtest Fatalf would
	// not).
	if golden.Version != ledgerVersion {
		t.Fatalf("ledger version %q, want %q", golden.Version, ledgerVersion)
	}
	if len(golden.Contract) != len(contractCases) {
		t.Fatalf("ledger has %d contract cases, suite has %d", len(golden.Contract), len(contractCases))
	}
	if len(golden.Candidates) != len(candProbes) {
		t.Fatalf("ledger has %d candidates, suite has %d", len(golden.Candidates), len(candProbes))
	}

	for i, cs := range cases {
		want := golden.Contract[i]
		if want.ID != cs.ID || want.Name != cs.Name {
			t.Fatalf("ledger contract[%d] = %s/%s, suite ran %s/%s — regenerate the ledger", i, want.ID, want.Name, cs.ID, cs.Name)
		}
		if !outcomesEqual(want.Agreed, cs.Agreed) {
			t.Errorf("contract case %s/%s: native outcome drifted from the adjudicated ledger:\n%s",
				cs.ID, cs.Name, diffOutcomes(cs.Name, want.Agreed, cs.Agreed))
		}
	}
	for i, p := range candProbes {
		want := golden.Candidates[i]
		if want.ID != p.id {
			t.Fatalf("ledger candidate[%d] = %s, suite ran %s — regenerate the ledger", i, want.ID, p.id)
		}
		if !outcomesEqual(want.Native, cands[p.id]) {
			t.Errorf("candidate %s (%s): native outcome drifted from the adjudicated ledger:\n%s",
				p.id, p.topic, diffOutcomes(p.id, want.Native, cands[p.id]))
		}
	}
}

// TestNativeRunLogRedaction scans the native engine log captured during a
// full case+probe run: no password, bind credential, or hash material may
// appear (contract section 5 rule 5; AGENTS.md logging rules).
func TestNativeRunLogRedaction(t *testing.T) {
	fx := compileFixture(t)
	ne := startNative(t, fx)
	t.Cleanup(func() { ne.close(t) })

	runContract(t, fx, ne)
	runCandidates(t, fx, ne)
	runControlPlane(t, startControlPlane(t, fx, ne))

	logs := ne.logs.String()
	secrets := []string{runtimePassword, nativeDMSecret}
	for _, pw := range userPasswords {
		secrets = append(secrets, pw)
	}
	// Also the rotated/new passwords used by the policy and control-plane cases.
	secrets = append(secrets, "parity-pwprobe-NEW-pass1", "parity-hist-second-01", "parity-zoe-secret-001",
		cpUserPass, cpUserPassNew, cpShortPass, "parity-cp-WRONG-00")
	for _, s := range secrets {
		if strings.Contains(logs, s) {
			t.Errorf("native engine log contains a secret value (%q...)", s[:12])
		}
	}
	if os.Getenv(ledgerUpdateEnv) != "" {
		t.Log("note: update mode set; this test never writes the ledger (integration run owns it)")
	}
}
